### ISSUE TITLE
Outdated Package Spotted - powderplayer

### ISSUE THREAD

**Issue by Xav83** [Xav83/chocolatey-packages#12]
So I look through the packages maintained by [dgtm](https://community.chocolatey.org/profiles/dtgm), to see if there is some packages that are outdated and GitHub projects, that I could maintain.

The package  [powderplayer](https://community.chocolatey.org/packages/powderplayer) seems to meet those criteria:
- The version `1.20` is the latest version on Chocolatey while the version `1.60` is available on [GitHub](https://github.com/jaruba/PowderPlayer/releases/tag/v1.60)

TODOs:
- [ ] Becoming a Maintainer of the package
  - [ ] Leave a comment to notify the current maintainer about the fact that the package is outdated
  - [ ] If there is no answer after one week, Then send a message via the option `Contact Maintainers`
  - [ ] If there is no answer after another week, Then contact the `Site Admins` to assess the situation
- [ ] After becoming a maintainer, then, we can create the package in [chocolatey-package repository](https://github.com/Xav83/chocolatey-packages)
- [ ] Once the package is uploaded and integrated, see if it is possible to specify the Chocolatey installation in `powderplayer` repository

**Comment by tunisiano187** [comment]
maintained by me ;-)

**Comment by Xav83** [comment]
Thank you @tunisiano187 :pray: 
And good luck maintaining all those packages! If you need any help, feel free to contact me, I'll help if I can :wink:
