### ISSUE TITLE
Outdated Package Spotted - litecoin

### ISSUE THREAD

**Issue by Xav83** [Xav83/chocolatey-packages#15]
So I look through the packages maintained by [dgtm](https://community.chocolatey.org/profiles/dtgm), to see if there is some packages that are outdated and GitHub projects, that I could maintain.

The package  [litecoin](https://community.chocolatey.org/packages/litecoin) seems to meet those criteria:
- The version `0.15.1` is the latest version on Chocolatey while the version `0.21.2.1` is available on [GitHub](https://github.com/litecoin-project/litecoin/releases/tag/v0.21.2.1)

TODOs:
- [ ] Becoming a Maintainer of the package
  - [ ] Leave a comment to notify the current maintainer about the fact that the package is outdated
  - [ ] If there is no answer after one week, Then send a message via the option `Contact Maintainers`
  - [ ] If there is no answer after another week, Then contact the `Site Admins` to assess the situation
- [ ] After becoming a maintainer, then, we can create the package in [chocolatey-package repository](https://github.com/Xav83/chocolatey-packages)
- [ ] Once the package is uploaded and integrated, see if it is possible to specify the Chocolatey installation in `litecoin` repository

**Comment by tunisiano187** [comment]
maintained by me ;-)
