### ISSUE TITLE
hidhide: install is not silent

### ISSUE THREAD

**Issue by soredake** [Xav83/chocolatey-packages#20]
when i tried installing hidhide with `choco install -y hidhide` i got this:
![hid_hide_not_installing_quietly](https://user-images.githubusercontent.com/5204968/228230906-aa253170-d192-4738-9718-96c20ca0d920.png)

**Comment by Xav83** [comment]
Hi @soredake,

First of all, thank you for you report and sorry for the late reply :slightly_smiling_face: 

This issue has been fixed on the latest version of the hidhide package :slightly_smiling_face:
