### ISSUE TITLE
Conan 1.59.0 is missing

### ISSUE THREAD

**Issue by stefansli** [Xav83/chocolatey-packages#22]
Hi, thank you very much for providing a conan recipe.
With the release of Conan 2.x I noticed, that no further versions of Conan 1.X have been provided. Any chance you could add them?
Especially since the current `conan` package will automatically update to Conan 2.0 which is not compatible. So maybe we need a new package called `conan1` or something similiar?

**Comment by Xav83** [comment]
Hi @vectorsli,

First of all, thank you for you report and sorry for the late reply :slightly_smiling_face: 

I've taken a look to all the versions available in Chocolatey, and in the `conan` official releases.
Apparently the following two versions are not present as Chocolatey packages:
- [1.62.0](https://github.com/conan-io/conan/releases/tag/1.62.0)
- [1.59.0](https://github.com/conan-io/conan/releases/tag/1.59.0) (which you reported)

The technical explication for why they are missing is the following: the CI process which pushes automatically the new versions, only push the latest one that it found, and those 1.x version has been pushed the same day than a 2.x version, so it has only pushed the 2.x version.

I am going to create the package for the version `1.62.0`, as it is the latest 1.x release of `conan` to date. :muscle: 

Do you want me to alaso create chocolatey package for the version `1.59.0` ? or are you already on a newer version (1.60.0 or 1.61.0) ?

**Comment by stefansli** [comment]
Hi @Xav83,

thank you for the response. I'm already on a newer version than `1.59.0`, so no need to create a package for it. When I initially created the ticket, I thought all 1.X packages will be missing, but thankfully that's not the case. I don't expect, there will be many more Conan 1.X releases. From my side, you can close this issue, once `1.62.0` is released.

**Comment by Xav83** [comment]
Well, the version [1.62.0](https://community.chocolatey.org/packages/conan/1.62.0) of conan package is available, and the version [1.59.0](https://community.chocolatey.org/packages/conan/1.59.0) following the Chocolatey validation process  :smile:

So you can already move on the version `1.62.0`, and the version `1.59.0` will be available if someone else needs it :wink:
