### ISSUE TITLE
Conan 1.64.1 is missing

### ISSUE THREAD

**Issue by stefansli** [Xav83/chocolatey-packages#31]
Hi @Xav83,

two weeks ago, Conan 1.64.1 was released. Shortly afterwards, a new Conan 2.X was released which probably interfered with the scheduled check for new Conan versions, picking Conan 2.X and skipping 1.64.1.

Could you please trigger a deploy of Conan 1.64.1?

Thanks in advance and regards,
Stefan

**Comment by Xav83** [comment]
Hi @stefansli,

Thank you a lot for this issue :slightly_smiling_face: 

I have added the versions [1.64.1](https://community.chocolatey.org/packages/conan/1.64.1) and [1.65.0](https://community.chocolatey.org/packages/conan/1.65.0) of the conan package.
